# -*- coding: utf-8 -*-
"""morph_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oGsrQ00a1_166cX1Fc89PNZx4P2x5vxu
"""

#morph_processing

from razdel import sentenize, tokenize
from navec import Navec
from slovnet import Morph

def analyze_morphology(text):
    navec = Navec.load('navec_news_v1_1B_250K_300d_100q.tar')
    morph_model = Morph.load('slovnet_morph_news_v1.tar', batch_size=4)
    morph_model.navec(navec)

    chunk = []
    for sent in sentenize(text):
        tokens = [_.text for _ in tokenize(sent.text)]
        chunk.append(tokens)

    results = []
    for markup in morph_model.map(chunk):
        for token in markup.tokens:
            results.append(f"{token.text:>20} {token.tag}\n")
    return results